FROM python:3.7-stretch

RUN pip install numpy pandas Pillow streamlit

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN mkdir -p /root/.streamlit

RUN bash -c 'echo -e "\
[general]\n\
email = \"\"\n\
" > /root/.streamlit/credentials.toml'

RUN bash -c 'echo -e "\
[server]\n\
port=8503\n\
enableCORS = false\n\
" > /root/.streamlit/config.toml'

EXPOSE 8503
RUN mkdir -p /home/app
COPY app/front_classifier.py /home/app/front_classifier.py
WORKDIR /home/app


CMD streamlit run front_classifier.py