FROM python:3.7-stretch

RUN pip install numpy pandas Pillow streamlit

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ARG APP_FOLDER=/home/app
ARG APP_NAME=front_classifier.py

RUN mkdir -p /root/.streamlit

RUN bash -c 'echo -e "\
[general]\n\
email = \"\"\n\
" > /root/.streamlit/credentials.toml'

RUN bash -c 'echo -e "\
[server]\n\
port=8503\n\
enableCORS = false\n\
" > /root/.streamlit/config.toml'

EXPOSE 8503
RUN mkdir -p $APP_FOLDER
COPY app/$APP_NAME $APP_FOLDER/$APP_NAME
WORKDIR $APP_FOLDER


CMD streamlit run front_classifier.py